### PR TITLE
Added a Youtube Icon

### PR DESCRIPTION
**Pull request by yashrsharma44**
Actually I made a PR from master, so made a PR from non-master branch.

### CODE REVIEW

**Comment by Parth-Vader** [comment]
Looks cool. Can you also make the links clickable instead of the text?

**Comment by yashrsharma44** [comment]
Okay. But I have to make a Seperate PR as it needs to include the recent commit #11

**Comment by Parth-Vader** [comment]
`git pull` and add to this PR itself.

**Comment by yashrsharma44** [comment]
Thanks.

**Comment by yashrsharma44** [comment]
Added the Hyperlink for the Videos.

**Comment by yashrsharma44** [comment]
Can you close this PR, if everything is fine?

**Comment by Parth-Vader** [comment]
@yashrsharma44 Why do you want to close this PR? Do you not want this to be merged?

I tested it - but the `Click To Open` link doesn't seem to work.

**Comment by yashrsharma44** [comment]
Sorry for that. I need to address some issues regarding the link, so I will correct it now.

**Comment by yashrsharma44** [comment]
I am not able to save the changes in this PR, so I need to close this PR and make a new PR. Please consider that.

**Pull request closed without merging**
