### PR TITLE
count and last visit

### PR DESCRIPTION
**Pull request by mritunjayz**

### CODE REVIEW

**Comment by Parth-Vader** [comment]
@mritunjaygoutam12 Can you also update the screenshot in README.md too?

**Comment by Parth-Vader** [comment]
Great work, can the video links present in the image be something more general (like the previous case)?

**Comment by Parth-Vader** [comment]
@mritunjaygoutam12 Are you willing to contribute more to this PR? :smile: It needs a little more work.

**Comment by yashrsharma44** [comment]
Can you state what else is missing in this PR?

**Comment by Parth-Vader** [comment]
@yashrsharma44 As mentioned, I need the screenshots to have videos more general - for example, python related videos.
If you're interested you can try adding commits to this PR. #14 is going to be merged.

**Pull request closed without merging**
