### PR TITLE
Added the Youtube Icon, CSS and Hyperlink.

### PR DESCRIPTION
**Pull request by yashrsharma44**

### CODE REVIEW

**Comment by yashrsharma44** [comment]
I have made a new PR after rectifying my mistakes in the earlier PR. Please consider that.

**Comment by Parth-Vader** [comment]
Looks good to me, was the pop up box intended when clicked on "Click to Open"?

**Comment by yashrsharma44** [comment]
Sorry, it was some sloppy work from me. I wanted to add the pop up when a bookmark is added, but added for the button, "Click to Open". Correcting it.

**Comment by Parth-Vader** [comment]
@yashrsharma44 It's alright - checking it again, but always test and try before adding a commit and sending a PR - and mention features added and bugs that remain.

**Review by Parth-Vader — APPROVED** [review]

**Comment by yashrsharma44** [comment]
Thanks. However, there is a bug that I wanted to discuss.
While extracting the title from the history, if I am viewing the video for the first time, the title is visible. However, when I replay the video, and try to save the bookmark, then the title is replaced by `Youtube`. So any ideas how to deal with that?

**Comment by Parth-Vader** [comment]
@yashrsharma44 Lets discuss in the slack group.

**Pull request merged**
