### PR TITLE
Add more info [MERGE+1]

### PR DESCRIPTION
**Pull request by mritunjayz**
#4

### CODE REVIEW

**Comment by Parth-Vader** [comment]
@mritunjaygoutam12 Great work. Can the `last seen` being displayed be modified to some human readable format?

**Comment by Parth-Vader** [comment]
@mritunjaygoutam12 Great Work. You can look at other issues as well.
Are you participating in KWoC?

**Comment by mritunjayz** [comment]
Yes,I am.

**Comment by mritunjayz** [comment]
making new pull request

**Comment by Parth-Vader** [comment]
@mritunjaygoutam12 Can you just send the PR for the date part, leaving the logo behind?

**Comment by aniketgattani** [comment]
Is someone working on this if not i would like to contribute

**Pull request closed without merging**
