### PR TITLE
Added the icon

### PR DESCRIPTION
**Pull request by vchrombie**
Added the favicon 

icon

Solves the issue #6, I guess.

### CODE REVIEW

**Comment by vchrombie** [comment]
All the demo images in the README.md are also updated according to the new icon.
Can you please review this PR now.

**Comment by Parth-Vader** [comment]
Thanks. Can the actual videos listed in the screenshot be changed some generic videos? Looks a little aesthetically weird to me. :grin:

**Comment by vchrombie** [comment]
Oh Sorry. 
I did not look at it.
It was my music list.

I will do that.

**Comment by vchrombie** [comment]
Now, it is fine, I guess.
Can you please review it.

**Comment by Parth-Vader** [comment]
Looks good to me, merging :)

**Pull request merged**
