### PR TITLE
Changed the CSS

### PR DESCRIPTION
**Pull request by yashrsharma44**
Added some CSS designs. Please review.

### CODE REVIEW

**Comment by Parth-Vader** [comment]
@yashrsharma44 Looks good, can the colors be more Youtube themed? Otherwise, this is good too.

**Comment by yashrsharma44** [comment]
Can you suggest any ideas about the color combination? As Youtube has only red and white, so simple colors are not vibrant enough to show out.

**Comment by yashrsharma44** [comment]
Does adding a favicon of youtube, serve the purpose?

**Comment by yashrsharma44** [comment]
Can you merge this PR, if everything is fine?

**Comment by Parth-Vader** [comment]
What does this PR do exactly?

**Comment by yashrsharma44** [comment]
This PR was made for adding CSS designs. However another PR was made including the commits containing the CSS. So this PR seems redundant. So I think it can be closed.

**Comment by Parth-Vader** [comment]
Cool, closing.

**Pull request closed without merging**
